(function () {
  var content = {
    about: {
      title: "About Us",
      html: [
        "<h2>About Us</h2>",
        "<p><em>Committed to providing a secure, stable, and fair online entertainment experience.</em></p>",
        "<p>This platform is a comprehensive online entertainment service for adult users, offering sports betting, live casino, slots, table games, card games, and lottery-style products. We place equal emphasis on compliant operations, technical reliability, user experience, and responsible risk control.</p>",
        "<h3>Platform Advantages</h3>",
        "<ul>",
        "<li><strong>Security and Stability:</strong> Multi-layer encryption, account protection, and transaction monitoring help protect user information and funds.</li>",
        "<li><strong>Fair Play:</strong> Game results are generated by independent systems or third-party providers to ensure transparent processes and random outcomes.</li>",
        "<li><strong>Diverse Products:</strong> Sports betting, live dealers, electronic games, card and table games, and lottery-style entertainment are available in one place.</li>",
        "<li><strong>Efficient Support:</strong> Customer service is available around the clock for account, deposit, withdrawal, promotion, and risk review inquiries.</li>",
        "</ul>",
        "<h3>Responsible Gaming</h3>",
        "<p>We advocate responsible entertainment and strictly prohibit participation by minors. Users should manage their entertainment budget according to their financial situation. If assistance is needed, customer support can help with self-exclusion, cooling-off periods, or account suspension requests.</p>",
        "<blockquote><p><strong>Our Commitment</strong><br/>We aim to provide adult users with a reliable, convenient, and responsible online entertainment environment built on strong user experience and security controls.</p></blockquote>",
        "<p><strong>Customer Support:</strong> 24/7 online assistance<br/><strong>Service Scope:</strong> Account support, deposits and withdrawals, promotion inquiries, and risk review appeals</p>"
      ].join("\n")
    },
    agreement: {
      title: "User Agreement",
      html: [
        "<h2>User Agreement</h2>",
        "<p><em>Last updated: January 1, 2026</em></p>",
        "<p><strong>Welcome to this platform.</strong></p>",
        "<p>Please read this agreement carefully before registering, logging in, or using the platform services. By clicking “Agree”, completing registration, or continuing to use the services, you confirm that you understand and accept this agreement.</p>",
        "<hr/>",
        "<h3>1. Eligibility</h3>",
        "<p>The platform is available only to users who have reached the legal age in their jurisdiction and have full legal capacity. Minors and users located in jurisdictions where online gaming or betting is prohibited must not register or use the platform services.</p>",
        "<h3>2. Service Description</h3>",
        "<p>The platform provides online entertainment information and services, including sports betting, live casino, electronic games, card and table games, and lottery-style products. Available products, promotion rules, settlement methods, and service scope are subject to the information displayed on the platform.</p>",
        "<p>The platform may adjust, suspend, or terminate certain services due to compliance requirements, operational arrangements, system maintenance, or risk control needs, and may notify users through announcements, messages, or page prompts.</p>",
        "<h3>3. Account Registration and Security</h3>",
        "<p>Users must provide true, accurate, and complete information for registration and identity verification, and must properly safeguard account credentials, passwords, verification codes, and payment information.</p>",
        "<p>Accounts are for personal use only and may not be transferred, rented, lent, or sold. Users are responsible for losses caused by improper custody, disclosure, or unauthorized sharing of account information.</p>",
        "<h3>4. Deposits, Withdrawals, and Settlement</h3>",
        "<p>Users must make deposits and withdrawals through channels approved by the platform. The platform may review transactions based on risk control, anti-money laundering requirements, promotion audits, or identity verification needs.</p>",
        "<p>If abnormal betting, arbitrage, repeated promotion abuse, false transactions, or other violations are identified, the platform may delay settlement, reclaim bonuses, freeze balances, or restrict account functions.</p>",
        "<h3>5. User Conduct</h3>",
        "<p>When using the platform services, users must not engage in any of the following activities:</p>",
        "<ul>",
        "<li>Impersonating others, using false information, or evading identity verification.</li>",
        "<li>Exploiting system vulnerabilities, odds errors, delayed data, or rule defects for profit.</li>",
        "<li>Money laundering, cash-out abuse, hedging, syndicate betting, bot betting, or other abnormal transactions.</li>",
        "<li>Publishing illegal, pornographic, violent, fraudulent, insulting, or rights-infringing content.</li>",
        "</ul>",
        "<p>If a user violates this agreement or platform rules, the platform may conduct risk reviews, restrict login, suspend withdrawals, cancel bonuses, freeze or close the account, or take other necessary measures.</p>",
        "<h3>6. Responsible Gaming</h3>",
        "<p>Users should participate in online entertainment responsibly and control both time and spending. Users who need login limits, deposit limits, cooling-off periods, or account suspension may contact customer support for assistance.</p>",
        "<h3>7. Intellectual Property</h3>",
        "<p>Platform pages, logos, text, images, audio and video materials, programs, data, and related content are protected by law. Without permission, users may not copy, distribute, adapt, scrape, or use such content for commercial purposes.</p>",
        "<h3>8. Agreement Updates</h3>",
        "<p>The platform may update this agreement according to laws, regulatory requirements, or operational needs. Continued use of the services after updates are published constitutes acceptance of the revised agreement.</p>"
      ].join("\n")
    }
  };

  var activeTab = "about";
  var editing = false;
  var draft = {};

  function $(selector, root) {
    return (root || document).querySelector(selector);
  }

  function $all(selector, root) {
    return Array.prototype.slice.call((root || document).querySelectorAll(selector));
  }

  function cloneContent() {
    draft = {
      about: { title: content.about.title, html: content.about.html },
      agreement: { title: content.agreement.title, html: content.agreement.html }
    };
  }

  function renderContent(source) {
    ["about", "agreement"].forEach(function (name) {
      $("#" + name + "Title").value = source[name].title;
      $("[data-preview=\"" + name + "\"]").innerHTML = source[name].html;
      $("[data-editor=\"" + name + "\"]").value = source[name].html;
      $("[data-live-preview=\"" + name + "\"]").innerHTML = source[name].html;
      $("[data-count=\"" + name + "\"]").textContent = source[name].html.length;
    });
  }

  function setActiveTab(name) {
    activeTab = name;
    $all(".tab-btn").forEach(function (btn) {
      btn.classList.toggle("is-active", btn.getAttribute("data-tab") === name);
    });
    $all(".content-panel").forEach(function (panel) {
      panel.classList.toggle("is-active", panel.getAttribute("data-panel") === name);
    });
  }

  function setEditing(value) {
    editing = value;
    $(".brand-panel").classList.toggle("is-editing", editing);
    $all(".title-input").forEach(function (input) {
      input.disabled = !editing;
    });
    if (editing) {
      cloneContent();
      renderContent(draft);
    } else {
      renderContent(content);
    }
  }

  function syncDraft(name) {
    draft[name].title = $("#" + name + "Title").value;
    draft[name].html = $("[data-editor=\"" + name + "\"]").value;
    $("[data-live-preview=\"" + name + "\"]").innerHTML = draft[name].html;
    $("[data-count=\"" + name + "\"]").textContent = draft[name].html.length;
  }

  document.addEventListener("DOMContentLoaded", function () {
    cloneContent();
    renderContent(content);
    setActiveTab(activeTab);

    $all(".tab-btn").forEach(function (btn) {
      btn.addEventListener("click", function () {
        setActiveTab(btn.getAttribute("data-tab"));
      });
    });

    $("[data-edit]").addEventListener("click", function () {
      setEditing(true);
    });

    $("[data-cancel]").addEventListener("click", function () {
      setEditing(false);
    });

    $("[data-save]").addEventListener("click", function () {
      syncDraft(activeTab);
      content.about = { title: draft.about.title, html: draft.about.html };
      content.agreement = { title: draft.agreement.title, html: draft.agreement.html };
      setEditing(false);
    });

    $all(".html-editor").forEach(function (editor) {
      editor.addEventListener("input", function () {
        syncDraft(editor.getAttribute("data-editor"));
      });
    });

    $all(".title-input").forEach(function (input) {
      input.addEventListener("input", function () {
        var name = input.id.replace("Title", "");
        if (draft[name]) {
          draft[name].title = input.value;
        }
      });
    });
  });
})();
