from __future__ import annotations

import shutil
from datetime import datetime
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor
from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
DOCX = ROOT / "B端后台操作手册.docx"
BACKUP_DIR = ROOT / "backups"
ASSET_DIR = ROOT / "custom" / "assets" / "manual-brand-settings"
SCREENSHOT = ASSET_DIR / "brand-settings-about-us.png"

FONT_NAME = "微软雅黑"
BLUE = RGBColor(47, 85, 151)
CAPTION_GRAY = RGBColor(112, 126, 146)


def image_font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    candidates = [
        "C:/Windows/Fonts/msyhbd.ttc" if bold else "C:/Windows/Fonts/msyh.ttc",
        "C:/Windows/Fonts/simhei.ttf",
        "C:/Windows/Fonts/arial.ttf",
    ]
    for item in candidates:
        path = Path(item)
        if path.exists():
            return ImageFont.truetype(str(path), size)
    return ImageFont.load_default()


def draw_text(draw: ImageDraw.ImageDraw, xy: tuple[int, int], text: str, font, fill=(15, 23, 42)) -> None:
    draw.text(xy, text, font=font, fill=fill)


def create_about_us_screenshot() -> None:
    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    width, height = 1514, 742
    img = Image.new("RGB", (width, height), (255, 255, 255))
    draw = ImageDraw.Draw(img)

    f_tab = image_font(14)
    f_label = image_font(14)
    f_input = image_font(15)
    f_h1 = image_font(30, True)
    f_h2 = image_font(20, True)
    f_body = image_font(15)
    f_body_bold = image_font(14, True)
    f_button = image_font(14)

    text = (15, 23, 42)
    muted = (71, 85, 105)
    border = (211, 219, 232)
    blue = (22, 119, 255)
    panel = (244, 247, 251)
    green = (35, 181, 126)

    draw.line((0, 50, width, 50), fill=border, width=1)
    draw_text(draw, (13, 17), "关于我们", f_tab, blue)
    draw_text(draw, (114, 17), "用户协议", f_tab, text)
    draw.line((8, 50, 75, 50), fill=blue, width=2)

    draw_text(draw, (70, 93), "标题", f_label, text)
    draw.rounded_rectangle((115, 79, 1495, 117), radius=3, fill=(248, 250, 252), outline=border)
    draw_text(draw, (129, 93), "About Us", f_input, muted)

    draw_text(draw, (70, 348), "内容", f_label, text)
    draw.rounded_rectangle((115, 139, 1495, 658), radius=3, fill=(255, 255, 255), outline=border)

    x, y = 140, 158
    draw_text(draw, (x, y), "About Us", f_h1, (30, 41, 59))
    y += 42
    draw_text(
        draw,
        (x, y),
        "Committed to providing a secure, stable, and fair online entertainment experience.",
        f_body,
        text,
    )
    y += 28
    paragraph = (
        "This platform is a comprehensive online entertainment service for adult users, offering sports betting, "
        "live casino, slots, table games, card games, and lottery-style products. We place equal emphasis"
    )
    draw_text(draw, (x, y), paragraph, f_body, text)
    y += 23
    draw_text(
        draw,
        (x, y),
        "on compliant operations, technical reliability, user experience, and responsible risk control.",
        f_body,
        text,
    )

    y += 36
    draw_text(draw, (x, y), "Platform Advantages", f_h2, (30, 41, 59))
    bullets = [
        ("Security and Stability", "Multi-layer encryption, account protection, and transaction monitoring help protect user information and funds."),
        ("Fair Play", "Game results are generated by independent systems or third-party providers to ensure transparent processes and random outcomes."),
        ("Diverse Products", "Sports betting, live dealers, electronic games, card and table games, and lottery-style entertainment are available in one place."),
        ("Efficient Support", "Customer service is available around the clock for account, deposit, withdrawal, promotion, and risk review inquiries."),
    ]
    y += 32
    for title, desc in bullets:
        draw_text(draw, (x + 5, y), "•", f_body, text)
        draw_text(draw, (x + 24, y), f"{title}:", f_body_bold, text)
        title_width = int(draw.textlength(f"{title}: ", font=f_body_bold))
        draw_text(draw, (x + 24 + title_width, y), desc, f_body, text)
        y += 23

    y += 16
    draw_text(draw, (x, y), "Responsible Gaming", f_h2, (30, 41, 59))
    y += 32
    draw_text(
        draw,
        (x, y),
        "We advocate responsible entertainment and strictly prohibit participation by minors. Users should manage their entertainment budget according to their financial situation. If assistance is needed,",
        f_body,
        text,
    )
    y += 23
    draw_text(
        draw,
        (x, y),
        "customer support can help with self-exclusion, cooling-off periods, or account suspension requests.",
        f_body,
        text,
    )

    y += 20
    draw.rectangle((140, y, 1470, y + 72), fill=panel)
    draw.rectangle((140, y, 144, y + 72), fill=green)
    draw_text(draw, (162, y + 17), "Our Commitment", f_body_bold, text)
    draw_text(
        draw,
        (162, y + 41),
        "We aim to provide adult users with a reliable, convenient, and responsible online entertainment environment built on strong user experience and security controls.",
        f_body,
        text,
    )

    y += 90
    draw_text(draw, (140, y), "Customer Support:", f_body_bold, text)
    support_width = int(draw.textlength("Customer Support: ", font=f_body_bold))
    draw_text(draw, (140 + support_width, y), "24/7 online assistance", f_body, text)
    y += 23
    draw_text(draw, (140, y), "Service Scope:", f_body_bold, text)
    scope_width = int(draw.textlength("Service Scope: ", font=f_body_bold))
    draw_text(
        draw,
        (140 + scope_width, y),
        "Account support, deposits and withdrawals, promotion inquiries, and risk review appeals",
        f_body,
        text,
    )

    draw.rounded_rectangle((801, 692, 864, 726), radius=4, fill=(64, 145, 247))
    draw_text(draw, (819, 702), "修改", f_button, (255, 255, 255))
    img.save(SCREENSHOT)


def set_run(run, *, size: float = 10, bold: bool = False, color: RGBColor | None = None) -> None:
    run.font.name = FONT_NAME
    run._element.rPr.rFonts.set(qn("w:eastAsia"), FONT_NAME)
    run._element.rPr.rFonts.set(qn("w:ascii"), FONT_NAME)
    run._element.rPr.rFonts.set(qn("w:hAnsi"), FONT_NAME)
    run.font.size = Pt(size)
    run.bold = bold
    if color is not None:
        run.font.color.rgb = color


def insert_after(paragraph, text: str = "", style: str | None = None):
    new_p = OxmlElement("w:p")
    paragraph._p.addnext(new_p)
    new_para = paragraph._parent.add_paragraph()
    new_para._p = new_p
    if style:
        new_para.style = style
    if text:
        new_para.add_run(text)
    return new_para


def delete_paragraph(paragraph) -> None:
    element = paragraph._element
    element.getparent().remove(element)
    paragraph._p = paragraph._element = None


def add_heading_after(anchor, text: str, level: int):
    paragraph = insert_after(anchor, style=f"Heading {level}")
    run = paragraph.add_run(text)
    size = 12.5 if level == 3 else 11
    set_run(run, size=size, bold=True, color=BLUE)
    paragraph.paragraph_format.space_after = Pt(5)
    return paragraph


def add_body_after(anchor, text: str):
    paragraph = insert_after(anchor, style="Normal")
    run = paragraph.add_run(text)
    set_run(run, size=10)
    paragraph.paragraph_format.space_after = Pt(3)
    paragraph.paragraph_format.line_spacing = 1.15
    return paragraph


def add_bullet_after(anchor, label: str, text: str):
    paragraph = insert_after(anchor, style="List Bullet")
    label_run = paragraph.add_run(label)
    set_run(label_run, size=10, bold=True, color=BLUE)
    body_run = paragraph.add_run("：" + text)
    set_run(body_run, size=10)
    paragraph.paragraph_format.space_after = Pt(3)
    paragraph.paragraph_format.line_spacing = 1.15
    return paragraph


def add_picture_after(anchor):
    paragraph = insert_after(anchor, style="Normal")
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    paragraph.add_run().add_picture(str(SCREENSHOT), width=Inches(6.45))
    paragraph.paragraph_format.space_after = Pt(2)
    return paragraph


def add_caption_after(anchor, text: str):
    paragraph = insert_after(anchor, style="Caption")
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = paragraph.add_run(text)
    set_run(run, size=9, color=CAPTION_GRAY)
    paragraph.paragraph_format.space_after = Pt(6)
    return paragraph


def remove_existing_platform_section(document: Document) -> None:
    start = None
    for index, paragraph in enumerate(document.paragraphs):
        if paragraph.text.strip() == "平台设置":
            start = index
            break
    if start is None:
        return

    end = len(document.paragraphs)
    for index in range(start + 1, len(document.paragraphs)):
        style_name = document.paragraphs[index].style.name
        if style_name in {"Heading 1", "Heading 2", "Heading 3"}:
            end = index
            break

    for paragraph in list(document.paragraphs[start:end]):
        delete_paragraph(paragraph)


def reset_brand_section(document: Document):
    start = None
    for index, paragraph in enumerate(document.paragraphs):
        if paragraph.style.name == "Heading 3" and paragraph.text.strip() == "品牌设置":
            start = index
            break
    if start is None:
        raise RuntimeError("未找到“品牌设置”章节。")

    end = len(document.paragraphs)
    for index in range(start + 1, len(document.paragraphs)):
        style_name = document.paragraphs[index].style.name
        if style_name in {"Heading 1", "Heading 2", "Heading 3"}:
            end = index
            break

    for paragraph in list(document.paragraphs[start + 1:end]):
        delete_paragraph(paragraph)

    anchor = document.paragraphs[start]
    for run in anchor.runs:
        set_run(run, size=12.5, bold=True, color=BLUE)
    return anchor


def main() -> None:
    if not DOCX.exists():
        raise FileNotFoundError(DOCX)

    create_about_us_screenshot()

    BACKUP_DIR.mkdir(exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup = BACKUP_DIR / f"{DOCX.stem}.brand-settings-{stamp}.bak.docx"
    shutil.copy2(DOCX, backup)

    document = Document(DOCX)
    remove_existing_platform_section(document)
    anchor = reset_brand_section(document)
    last = add_body_after(
        anchor,
        "品牌设置用于维护前台品牌说明类内容，本次包含“关于我们”和“用户协议”两个页签。运营人员可在页签内查看标题和正文内容，点击页面底部“修改”进入编辑状态，调整后保存并同步到前台对应展示页面。",
    )

    last = add_heading_after(last, "关于我们", 4)
    last = add_picture_after(last)
    last = add_caption_after(last, "图16：品牌设置-关于我们，用于维护前台 About Us 展示内容。")
    for label, text in [
        ("标题", "当前示例为 About Us，用于配置前台关于我们页面或弹层的展示标题。标题应简洁明确，并与站点语言和品牌定位保持一致。"),
        ("内容", "正文区域支持维护平台介绍、平台优势、责任博彩说明、服务范围和承诺说明等内容。发布前需检查段落层级、英文拼写、品牌措辞和合规表达。"),
        ("修改", "点击底部“修改”进入编辑状态；保存前应由运营或合规人员复核内容，避免出现过期承诺、错误服务范围或与站点实际能力不一致的描述。"),
    ]:
        last = add_bullet_after(last, label, text)

    last = add_heading_after(last, "用户协议", 4)
    last = add_body_after(
        last,
        "用户协议页签与关于我们页签的页面结构基本一致，同样由顶部页签、标题输入框、内容编辑区域和底部修改按钮组成，因此手册不再重复放图。维护时切换到“用户协议”页签，核对协议标题、适用用户范围、账号使用规则、充值提现条款、风险提示、责任限制、隐私与合规说明等内容；修改并保存后，应同步检查前台用户协议入口展示是否更新。",
    )
    for label, text in [
        ("标题", "建议使用“用户协议”或当前站点约定的正式协议名称，避免与隐私政策、活动规则等其他文本混用。"),
        ("内容", "协议正文应覆盖用户注册、账号安全、服务使用、交易与结算、禁止行为、责任限制、争议处理和更新生效规则等关键条款。"),
        ("使用要点", "协议内容通常具有合规属性，修改前应确认审批流程；上线后建议抽查注册页、登录页、个人中心或页脚入口，确保用户看到的是最新版本。"),
    ]:
        last = add_bullet_after(last, label, text)

    document.save(DOCX)
    print(f"backup={backup}")
    print(f"screenshot={SCREENSHOT}")


if __name__ == "__main__":
    main()
